version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-frontend:
    executor: node/default
    working_directory: ~/project/hello-world-frontend
    steps:
      - checkout
      - run:
          name: Check for frontend changes
          command: |
            if git diff --quiet HEAD^ HEAD -- hello-world-frontend/; then
              echo "No changes in frontend. Skipping build and deploy."
              exit 0
            fi
      - node/install-packages:
          app-dir: hello-world-frontend
          pkg-manager: npm
      - run:
          name: Build Frontend
          command: npm run build
      - run:
          name: Deploy to Vercel
          command: |
            npm install -g vercel
            vercel deploy --prod --token $VERCEL_TOKEN

  build-backend:
    executor: node/default
    working_directory: ~/project/hello-world-backend
    steps:
      - checkout
      - run:
          name: Check for backend changes
          command: |
            if git diff --quiet HEAD^ HEAD -- hello-world-backend/; then
              echo "No changes in backend. Skipping build and deploy."
              exit 0
            fi
      - node/install-packages:
          app-dir: hello-world-backend
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-backend .
      - run:
          name: Deploy to Render
          when: on_success
          command: |
            curl -X POST \
            -H 'Accept: application/json' \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            'https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys'

workflows:
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: main
      - build-backend:
          filters:
            branches:
              only: main
