version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-frontend:
    executor: node/default
    working_directory: ~/project/hello-world-frontend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Build Frontend
          command: npm run build
      - run:
          name: Install Vercel Locally
          command: npm install vercel --save-dev
      - run:
          name: Deploy to Vercel
          command: npx vercel deploy --prod --token $VERCEL_TOKEN

  build-backend:
    machine: true
    working_directory: ~/project/hello-world-backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install Backend Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-backend .
      - run:
          name: Deploy to Render
          command: |
            curl -X POST \
            -H 'Accept: application/json' \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            'https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys'

workflows:
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: main
      - build-backend:
          filters:
            branches:
              only: main
