version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-backend:
    machine: true
    working_directory: ~/project/hello-world-backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install Backend Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Docker Image
          command: docker build -t hello-world-backend .
      - run:
          name: Deploy to Render
          command: |
            curl -X GET "$RENDER_DEPLOY_HOOK_URL"

workflows:
  build-and-deploy:
    jobs:
      - build-backend:
          filters:
            branches:
              only: main
